# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-05 00:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notesmerge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Merge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('result', models.TextField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.RemoveField(
            model_name='usage',
            name='usage_session',
        ),
        migrations.CreateModel(
            name='MergeOptions',
            fields=[
                ('input_delimeter', models.CharField(blank=True, default='\n\n', max_length=100)),
                ('output_delimeter', models.CharField(blank=True, default='\n\n', max_length=100)),
                ('remove_stop_words', models.BooleanField(default=False)),
                ('porter_stemmer', models.BooleanField(default=False)),
                ('wordnet_lemmatizer', models.BooleanField(default=False)),
                ('lowercase', models.BooleanField(default=False)),
                ('alphanumeric_filter', models.BooleanField(default=False)),
                ('alpha_filter', models.BooleanField(default=False)),
                ('numeric_filter', models.BooleanField(default=False)),
                ('merge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='notesmerge.Merge')),
            ],
        ),
        migrations.DeleteModel(
            name='Usage',
        ),
        migrations.DeleteModel(
            name='UsageSession',
        ),
        migrations.AddField(
            model_name='input',
            name='merge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notesmerge.Merge'),
        ),
    ]
