# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-07 01:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notesmerge', '0003_merge_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mergeoptions',
            old_name='input_delimeter',
            new_name='input_delimiter',
        ),
        migrations.RenameField(
            model_name='mergeoptions',
            old_name='output_delimeter',
            new_name='output_delimiter',
        ),
        migrations.AlterField(
            model_name='input',
            name='merge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='notesmerge.Merge'),
        ),
        migrations.AlterField(
            model_name='merge',
            name='result',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mergeoptions',
            name='merge',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='merge_options', serialize=False, to='notesmerge.Merge'),
        ),
    ]
