# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-07 06:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notesmerge', '0004_auto_20170107_0141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='input',
            old_name='input',
            new_name='text',
        ),
    ]
